# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Predefender
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

author:
  name: rjohnsen
  email: rogercbjohnsen@gmail.com

description: >
  Predefender is dedicated to advancing the next phase in Security Operations 
  Centers (SOCs). We focus on empowering SOC analysts with cutting-edge threat 
  hunting capabilities. We offer resources and training materials that are designed 
  to enhance your skills in proactively identifying and mitigating cyber threats.
  Join us as we transform reactive security measures into proactive threat hunting 
  strategies. Dive in to elevate your SOC's defense mechanisms and stay ahead of 
  emerging threats.

# Social media
github_username: rjohnsen
linkedin_username: rogerjohnsen
# telegram_username: rjohnsen

header_pages:
  - resources.md
  - software.md
  - about.md

social_links:
  - { platform: github, user_url: "https://github.com/rjohnsen" }
  - { platform: linkedin, user_url: "https://www.linkedin.com/in/rogerjohnsen" }
  - { platform: telegram, user_url: "https://t.me/rjohnsen" }

# Build settings
markdown: kramdown

#theme: minima
# remote_theme: jekyll/minima
remote_theme: "jeffreytse/jekyll-theme-yat"
# minima:
#  skin: dark

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
